### ISSUE TITLE
Bootloader/TEE support: when is it needed?

### ISSUE THREAD

**Issue by leandrofriedrich** [BlackMesa123/android_device_samsung_a54x#2]
Hi Salvo, first off, welcome back we missed you

I was wondering at which stage the whole TEE/BL Support tar thingies are needed? for booting in general? or is it just for decryption/whatever? maybe you can give me an answer, since my LOS Recovery build seems to get stuck at the bootlogo and i cant easily debug

**Comment by salvogiangri** [comment]
https://github.com/salvogiangri/android_device_samsung_a54x/commit/3b5bdb433a78ffc69f7a925a757cf7dc75048acb

**Comment by leandrofriedrich** [comment]
> [3b5bdb4](https://github.com/salvogiangri/android_device_samsung_a54x/commit/3b5bdb433a78ffc69f7a925a757cf7dc75048acb)

hmm will try adding it like that in my sources lets see what happens

**Comment by salvogiangri** [comment]
LineageOS recovery doesn't supports decryption, so you don't need to include crypto support.

**Comment by leandrofriedrich** [comment]
> LineageOS recovery doesn't supports decryption, so you don't need to include crypto support.

ah okay, so having/not having it shouldnt hinder it from booting or what do you mean

**Comment by salvogiangri** [comment]
Your issue has nothing to do with TEE/crypto services.

**Comment by leandrofriedrich** [comment]
thats both a relief and makes me more confused, i think ill stop for the night. btw by any chance do you have any debugging tips? i dont seem to have any usb activity so i cant pull logcats  etc.
